### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by rpavantica** [jcarr98/boostnote-extractor#1]
I don't wanna learn Phyton right now, but can find it heart to explain how to use this?

Also I haven't found a good app for my notes, what are using? Notable seems to be ok, but it has issues.

**Comment by jeffrey-carr** [comment]
I had been using Boostnote until it crashed. I've switched to [Typora](https://typora.io/) and it seems pretty good.

To use this, put it wherever your notes are saved and use the command line `python3 NoteExtractor.py` (or `python NoteExtractor.py` depending on how Python is installed on your computer) and it should just automatically extract all your notes.
